version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloomberg-app-container
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bloombergdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
